import type { Track } from "./types.ts";

export const sampleTracks = [
  {
    id: "trk-house-rising-sun",
    title: "House of the Rising Sun",
    artist: "Traditional reference",
    bpm: 84,
    key: {
      tonic: "A",
      mode: "dorian",
      variant: "variable-degree",
    },
    chordProgression: ["Am", "C", "D", "F"],
    confidence: {
      bpm: "confirmed",
      chords: "confirmed",
      key: "confirmed",
    },
    harmonyNotes:
      "Reference case for A Dorian with both F and F#. Treat the transition into plain A minor carefully.",
    comment: "Useful as a calibration track for variable-degree placement.",
    durationSeconds: 266,
    tags: ["reference", "modal-mixture"],
  },
  {
    id: "trk-berimbau",
    title: "Berimbau",
    artist: "Baden Powell",
    bpm: 118,
    key: {
      tonic: "D",
      mode: "dorian",
      variant: "diatonic",
    },
    chordProgression: ["Dm7", "G7", "Dm7", "A7"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    durationSeconds: 196,
    tags: ["samba", "mpb"],
  },
  {
    id: "trk-agua-de-beber",
    title: "Agua de Beber",
    artist: "Antonio Carlos Jobim",
    bpm: 132,
    key: {
      tonic: "C",
      mode: "natural-minor",
      variant: "diatonic",
    },
    chordProgression: ["Cm7", "F7", "Cm7", "G7"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    durationSeconds: 151,
    tags: ["bossa", "minor"],
  },
  {
    id: "trk-mas-que-nada",
    title: "Mas Que Nada",
    artist: "Jorge Ben",
    bpm: 104,
    key: {
      tonic: "G",
      mode: "natural-minor",
      variant: "raised-leading-tone",
    },
    chordProgression: ["Gm", "C7", "Gm", "D7"],
    confidence: {
      bpm: "confirmed",
      chords: "estimated",
      key: "confirmed",
    },
    comment: "Reliable energy bridge after slower samba-rock material.",
    durationSeconds: 178,
    tags: ["samba-rock", "classic"],
  },
  {
    id: "trk-canto-de-ossanha",
    title: "Canto de Ossanha",
    artist: "Baden Powell",
    bpm: 122,
    key: {
      tonic: "D",
      mode: "phrygian",
      variant: "diatonic",
    },
    chordProgression: ["Dm", "Eb", "Dm", "C"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    harmonyNotes: "Phrygian color is strong; avoid treating the flat second as a passing accident.",
    durationSeconds: 214,
    tags: ["afro-samba", "phrygian"],
  },
  {
    id: "trk-samba-de-verao",
    title: "Samba de Verao",
    artist: "Marcos Valle",
    bpm: 126,
    key: {
      tonic: "F",
      mode: "major",
      variant: "diatonic",
    },
    chordProgression: ["Fmaj7", "Gm7", "Am7", "Ab7"],
    confidence: {
      bpm: "confirmed",
      chords: "estimated",
      key: "estimated",
    },
    durationSeconds: 151,
    tags: ["bossa", "sunny"],
  },
  {
    id: "trk-garota-ipanema",
    title: "Garota de Ipanema",
    artist: "Tom Jobim",
    bpm: 128,
    key: {
      tonic: "F",
      mode: "major",
      variant: "diatonic",
    },
    chordProgression: ["Fmaj7", "G7", "Gm7", "C7"],
    confidence: {
      bpm: "confirmed",
      chords: "estimated",
      key: "confirmed",
    },
    durationSeconds: 165,
    tags: ["bossa", "standard"],
  },
  {
    id: "trk-taj-mahal",
    title: "Taj Mahal",
    artist: "Jorge Ben Jor",
    bpm: 112,
    key: {
      tonic: "A",
      mode: "mixolydian",
      variant: "diatonic",
    },
    chordProgression: ["A7", "G", "D", "A7"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    durationSeconds: 199,
    tags: ["samba-rock", "groove"],
  },
  {
    id: "trk-pais-tropical",
    title: "Pais Tropical",
    artist: "Jorge Ben Jor",
    bpm: 116,
    key: {
      tonic: "E",
      mode: "mixolydian",
      variant: "variable-degree",
    },
    chordProgression: ["E7", "A", "D", "E"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    harmonyNotes: "Mixolydian center may collapse into major depending on the loop section.",
    durationSeconds: 210,
    tags: ["samba-rock", "variable"],
  },
  {
    id: "trk-cravo-canela",
    title: "Cravo e Canela",
    artist: "Milton Nascimento",
    bpm: 108,
    key: {
      tonic: "G",
      mode: "lydian",
      variant: "diatonic",
    },
    chordProgression: ["Gmaj7", "A", "Gmaj7", "D"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    durationSeconds: 188,
    tags: ["mpb", "lydian"],
  },
  {
    id: "trk-aquarela",
    title: "Aquarela do Brasil",
    artist: "Ary Barroso",
    bpm: 146,
    key: {
      tonic: "A#",
      mode: "major",
      variant: "diatonic",
    },
    chordProgression: ["A#6", "Cm7", "F7", "A#6"],
    confidence: {
      bpm: "confirmed",
      chords: "estimated",
      key: "confirmed",
    },
    durationSeconds: 181,
    tags: ["samba", "classic"],
  },
  {
    id: "trk-consolacao",
    title: "Consolacao",
    artist: "Baden Powell",
    bpm: 120,
    key: {
      tonic: "C#",
      mode: "dorian",
      variant: "diatonic",
    },
    chordProgression: ["C#m7", "F#7", "C#m7", "G#7"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    durationSeconds: 205,
    tags: ["afro-samba", "dorian"],
  },
  {
    id: "trk-batuque",
    title: "Batuque Control",
    artist: "Sketch",
    bpm: 130,
    key: {
      tonic: "D#",
      mode: "natural-minor",
      variant: "raised-leading-tone",
    },
    chordProgression: ["D#m", "B", "A#7", "D#m"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    comment: "Synthetic placeholder for dense imported data.",
    durationSeconds: 224,
    tags: ["percussion", "draft"],
  },
  {
    id: "trk-maracatu-step",
    title: "Maracatu Step",
    artist: "Sketch",
    bpm: 126,
    key: {
      tonic: "G#",
      mode: "phrygian",
      variant: "variable-degree",
    },
    chordProgression: ["G#m", "A", "E", "F#"],
    confidence: {
      bpm: "estimated",
      chords: "estimated",
      key: "estimated",
    },
    harmonyNotes:
      "Variable phrygian area. Check whether A-natural is structural or just percussion-bed color.",
    durationSeconds: 239,
    tags: ["maracatu", "variable"],
  },
] as const satisfies readonly Track[];
